config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :files do 
    get 'tag'
    post :add_tags
    patch :share_file
    get 'download_file'
  end

  resources :tags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord

  mount_uploader :document, DocumentUploaderUploader
  ATTACHMENT_OPTIONS = %w(Public Private)
  belongs_to :user

  has_many :attachment_tags
  has_many :tags, through: :attachment_tags

  validate :file_size

  validates :attachment_type, :inclusion => {:in => ATTACHMENT_OPTIONS}

  validates_presence_of :title, :description, :attachment_type, :document

  def file_size
    size = document.file.size.to_f
    if size > 1.gigabytes.to_f
      errors.add(:document, "You cannot upload file greater than 1GB")
    end
 end
end

app/models/attachment_tag.rb
class AttachmentTag < ApplicationRecord
  attr_accessor :tag_id, :attachment_id
  belongs_to :tag
  belongs_to :attachment
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :attachment_tags
  has_many :attachments, through: :attachment_tags 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :attachments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :info, :danger, :warning

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:full_name, :email, :password, :current_password)}
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @files = current_user.attachments
  end

  def new
    @file = current_user.attachments.new
  end

  def create
    @file = current_user.attachments.new(attachment_params)
    @file.attachment_type = 'Private'
    if @file.save
      flash[:info] = "File Created Successfully."
      redirect_to files_path
    else
      @file = current_user.attachments.new
      render 'new'
    end
  end

  def tag
    @file = current_user.attachments.find_by_id(params[:file_id])
    @tags = Tag.all
  end

  def add_tags
    @file = current_user.attachments.find_by_id(params[:file_id])
    params[:tags].each do |tag_id|
      tag = Tag.find(tag_id)
      @file.attachment_tags.create(tag: tag)
    end
    flash[:info] = "Added Tag Successfully."
    redirect_to files_path
  end

  def download_file
    @file = Attachment.find(params[:file_id])
    send_file(@file.document.path,
          :filename =>File.basename(@file.document.path),
          :type => @file.document.content_type,
          :disposition => 'attachment',
          :url_based_filename => true)
  end

  private


  def attachment_params
    params.require(:attachment).permit(:title, :description, :document)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def show
    @tag = Tag.find(params[:id])
    @files = @tag.attachments.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/files/index.html.erb
<h2>My Files</h2>

<div class="ma-5">
  <h2>File Details</h2>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Files</button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">File</th>
            <th scope="col">Tags</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @files.each_with_index do |file, i|%>
            <tr>
              <th scope="row"><%= i + 1%></th>
              <td><%= file.title%></td>
              <td><%= file.description%>Gram</td>
              <td><%= link_to File.basename(file.document.path), file_download_file_path(file)%></td>
              <td>
                <%file.tags.each do |tag|%>
                  <span><%= link_to tag.name, tag_path(tag)%> </span>
                <%end%>
              </td>
              <td><%= link_to 'Add Tag', file_tag_path(file), class: "btn btn-primary btn-sm" %></td>

            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/files/new.html.erb
<h2>Create New File</h2>
<%= form_for @file, url: files_path, method: :post do |f| %>
  <% if @file.errors.full_messages.any? %>
    <% @file.errors.full_messages.each do |error_message| %>
      <%= error_message if @file.errors.full_messages.first == error_message %> <br />
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description%>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :attachment %><br />
    <%= f.file_field :document, class: 'form-control' %>
  </div>

  <div class="mt-3">
    <%= f.submit "Create File", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/files/show.html.erb
<div class="float-right">
  <p><%= link_to "Home", root_path%></p>
  <p class="ml-2"><%= link_to "Orders", couriers_path %></p>
</div>
<div class= "d-flex justify-content-center"><h3> Welcome to Order Page</h3></div>

<div class="mt-5 mb-5">
  <div class="row">
    <div class="col-6">
      Order Number
    </div>
    <div class="col-6">
      <%= @courier.order_number%>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Weight
    </div>
    <div class="col-6">
      <%= @courier.weight%> Gram
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Status
    </div>
    <div class="col-6">
      <%= @courier.status%>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Service Type
    </div>
    <div class="col-6">
      <%= @courier.service_type%>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Payment Mode
    </div>
    <div class="col-6">
      <%= @courier.payment_mode%>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Cost
    </div>
    <div class="col-6">
      <%= @courier.cost%> Rs.
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Sender
    </div>
    <div class="col-6">
      <%= @courier.user.full_name%>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Address
    </div>
    <div class="col-6">
      <%= @courier.address.full_address%>
    </div>
  </div>
</div>

app/views/files/tag.html.erb
<div class= "d-flex justify-content-center"><h3> Welcome to File Show</h3></div>

<div class="mt-5 mb-5">
  <div class="row">
    <div class="col-6">
      Title
    </div>
    <div class="col-6">
      <%= @file.title %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      Description
    </div>
    <div class="col-6">
      <%= @file.description%>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      File
    </div>
    <div class="col-6">
      <%= link_to File.basename(@file.document.path), file_download_file_path(@file)%>
    </div>
  </div>
</div>

<h2>Add Tags</h2>
<%= form_tag file_add_tags_path(@file), method: :post do %>
  <div class="form-group">

    <%= select_tag "tags[]", options_for_select(@tags.pluck(:name, :id)), { :multiple => true, class: 'form-control' } %>
  </div>

  <div class="mt-3">
    <%= submit_tag "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/home/index.html.erb
<header class="py-5">
  <div class="container px-lg-5">
    <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
      <div class="m-4 m-lg-5">
        <h1 class="display-5 fw-bold">A warm welcome to Pay Review Test!</h1>
        <p class="fs-4">Test App</p>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small bg-dark py-5 fixed-bottom">
  <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Utilize 2021</p></div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-lg-5">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user.present?%>
          <li class="nav-item">
            <%= link_to "New File", new_file_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My File", files_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UtilizeTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type%>">
        <%= msg %>
      </div>
    <% end %>
    <section class="pt-4">
      <div class="container px-lg-5">
        <%= yield %>
      </div>
    </section>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/tags/show.html.erb
<h2>Files for <%= @tag.name%></h2>

<div class="ma-5">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Files</button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">File</th>
          </tr>
        </thead>
        <tbody>
          <% @files.each_with_index do |file, i|%>
            <tr>
              <th scope="row"><%= i + 1%></th>
              <td><%= file.title%></td>
              <td><%= file.description%>Gram</td>
              <td><%= link_to File.basename(file.document.path), file_download_file_path(file)%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>